In [1]:
import pandas as pd
import numpy as np
import os
import random
random.seed(100)
os.chdir('/home/sunil/Desktop/datahack')
train = pd.read_csv('train.csv')

In [2]:
train.shape

(614, 13)

In [3]:
train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
train.rename(columns={'Loan_Status': 'class'}, inplace=True)

In [5]:
train.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
class                 object
dtype: object

In [6]:
train.isnull().values.any()

True

In [7]:
train=train.dropna()

In [8]:
train.shape

(480, 13)

In [9]:
train.isnull().values.any()

False

In [10]:
for col_name in train.columns:
    if(train[col_name].dtype == 'object'):
        train[col_name]= train[col_name].astype('category')
        train[col_name] = train[col_name].cat.codes

In [11]:
train.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
1        0       1        1           1          0              0   
2        1       1        1           0          0              1   
3        2       1        1           0          1              0   
4        3       1        0           0          0              0   
5        4       1        1           2          0              1   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   

   Credit_History  Property_Area  class  
1             1.0              0      0  
2             1.0              2      1  
3             1.0              2      1  
4             1.0              2      1  
5             1.0              2      1

In [12]:
X = train.drop('class', axis=1)  
X = X.drop('Loan_ID',axis=1)
y = train['class'] 

In [13]:
X.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
1       1        1           1          0              0             4583   
2       1        1           0          0              1             3000   
3       1        1           0          1              0             2583   
4       1        0           0          0              0             6000   
5       1        1           2          0              1             5417   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   

   Property_Area  
1              0  
2              2  
3              2  
4              2  
5              2

In [14]:
y.head()

1    0
2    1
3    1
4    1
5    1
Name: class, dtype: int8

In [15]:
X.apply(lambda x: x.value_counts()).T.stack()

Gender            0.0        86.0
                  1.0       394.0
Married           0.0       169.0
                  1.0       311.0
Dependents        0.0       274.0
                  1.0        80.0
                  2.0        85.0
                  3.0        41.0
Education         0.0       383.0
                  1.0        97.0
Self_Employed     0.0       414.0
                  1.0        66.0
ApplicantIncome   150.0       1.0
                  645.0       1.0
                  1000.0      1.0
                  1025.0      1.0
                  1299.0      1.0
                  1378.0      1.0
                  1442.0      1.0
                  1500.0      1.0
                  1538.0      1.0
                  1600.0      1.0
                  1625.0      1.0
                  1668.0      1.0
                  1759.0      1.0
                  1782.0      1.0
                  1800.0      2.0
                  1809.0      1.0
                  1811.0      1.0
              

In [16]:
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y.values,train_size=0.90, test_size=0.10)

In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((432, 11), (48, 11), (432,), (48,))

In [18]:
X_train_array=X_train.values
X_test_array=X_test.values

In [19]:
print(type(X_train_array))
print(type(X_test_array))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [20]:
#X_train_array=X_train_array.toarray()
#X_test_array=X_test_array.toarray()

In [21]:
y_test

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1], dtype=int8)

In [22]:
X_test_array

array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 2.89500000e+03, 0.00000000e+00, 9.50000000e+01,
        3.60000000e+02, 1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.51000000e+03, 0.00000000e+00, 7.60000000e+01,
        3.60000000e+02, 0.00000000e+00, 2.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.02500000e+03, 2.77300000e+03, 1.12000000e+02,
        3.60000000e+02, 1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 3.45000000e+03, 2.07900000e+03, 1.62000000e+02,
        3.60000000e+02, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.66660000e+04, 0.00000000e+00, 2.75000000e+02,
        3.60000000e+02, 1.00000000e+00, 2.00000000e+

In [23]:
type(X_test_array)

numpy.ndarray

In [24]:
X_test

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
498       1        1           1          0              1             2895   
17        0        0           0          0              0             3510   
418       1        1           0          0              0             1025   
470       1        1           1          0              1             3450   
572       1        1           2          0              0            16666   
124       1        1           0          1              0             4300   
108       1        1           2          0              0             3800   
169       1        1           2          0              0             8000   
350       1        1           0          0              0             9083   
57        1        1           0          0              0             3366   
343       1        1           3          1              0             3173   
247       1        1           1          1              0             6608   
3         1        1           0          1              0             2583   
90        1        1           0          0              0             2958   
482       1        1           0          0              0             2083   
18        1        1           0          1              0             4887   
378       1        0           0          0              0             3069   
69        0        0           0          0              0             4300   
262       0        0           1          0              0             3481   
578       1        1           1          0              0             1782   
360       0        0           1          0              0             4723   
596       1        1           2          1              1             6383   
59        1        1           2          1              0             3357   
106       1        1           2          0              0            11417   
452       1        1           0          0              0             3948   
599       1        1           2          0              0             5780   
428       1        1           0          0              0             2920   
91        1        1           2          0              0             6250   
484       1        1           2          0              0             8333   
64        0        0           0          0              0             4166   
321       1        1           3          0              0             4342   
330       1        0           1          0              0             4384   
575       1        1           2          0              0             3159   
508       1        1           0          0              1             2479   
608       1        1           0          0              0             3232   
394       1        1           2          0              0             3100   
221       1        1           2          0              0             4009   
166       0        1           0          0              0             4583   
173       1        1           0          0              0             5708   
147       1        1           1          0              0             1538   
155       1        1           3          0              0            39999   
368       1        1           1          0              0             6325   
532       1        0           2          0              0             3588   
4         1        0           0          0              0             6000   
456       1        1           0          0              0             4301   
613       0        0           0          0              1             4583   
281       1        1           0          0              0             3927   
500       0        0           0          0              0              645   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
498           0.000000        95.0             360.0         

In [25]:
X_train_array

array([[  1.,   1.,   0., ..., 360.,   1.,   2.],
       [  1.,   1.,   0., ..., 360.,   1.,   2.],
       [  0.,   0.,   0., ..., 360.,   1.,   2.],
       ...,
       [  1.,   1.,   1., ..., 360.,   1.,   2.],
       [  1.,   0.,   0., ..., 360.,   1.,   2.],
       [  1.,   1.,   0., ..., 360.,   1.,   2.]])

In [26]:
X_train

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
271       1        1           0          0              0            11146   
397       1        1           0          0              0             3033   
270       0        0           0          0              0             3237   
531       1        1           3          0              0             4281   
415       0        0           0          0              0             2995   
472       1        1           3          0              0             4691   
351       1        0           0          0              0             8750   
161       1        1           0          0              0             7933   
267       1        1           3          0              0             4333   
47        1        1           0          0              0             5821   
76        1        0           0          0              0             3750   
315       1        1           1          1              0             3399   
541       0        0           0          0              0             2138   
253       1        1           1          1              0             2661   
487       1        1           1          0              0            18333   
347       1        1           2          1              0             3083   
402       1        0           0          0              0             2500   
230       1        1           1          0              0             2491   
528       1        0           1          1              0             2679   
383       1        0           0          0              1             7167   
241       1        1           1          1              0             2510   
509       0        0           1          0              0            13262   
143       1        1           0          0              0             2698   
439       0        1           0          1              1             7142   
46        1        1           1          0              0             5649   
534       0        0           0          1              1            18165   
454       1        0           0          0              1             7085   
362       1        1           0          0              0             4750   
239       1        1           1          0              0             3315   
538       1        1           0          1              0             2917   
..      ...      ...         ...        ...            ...              ...   
58        1        1           1          0              0             8080   
299       1        1           1          0              0             2014   
568       0        0           0          0              0             2378   
448       1        1           2          0              0             3340   
92        1        1           2          1              0             3273   
591       1        1           2          0              1             6000   
386       1        0           0          1              0             2346   
33        1        1           0          0              0             3500   
149       1        1           0          0              0             4860   
555       1        1           1          0              0             5468   
141       1        0           0          0              0             5417   
37        0        1           0          0              0             3667   
133       1        1           0          0              1             3459   
340       1        1           3          1              0             2647   
408       1        1           1          0              0             8300   
492       1        0           0          1              0             3691   
420       1        1           0          0              0             5829   
427       1        1           2          0              0             5935   
274       1        1           2          0            

In [27]:
type(X_train_array)

numpy.ndarray

In [28]:
type(y_train)

numpy.ndarray

In [29]:
y_train

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [30]:
import numpy as np 
np.shape(X_train_array)

(432, 11)

In [31]:
np.shape(X_test_array)

(48, 11)

In [32]:
tpot = TPOTClassifier(verbosity=2, max_time_mins=2)
tpot.fit(X_train_array, y_train)

/home/sunil/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


Generation 1 - Current best internal CV score: 0.8054958567228014

2.0477756333333335 minutes have elapsed. TPOT will close down.
TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: BernoulliNB(input_matrix, alpha=0.1, fit_prior=True)


TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
        disable_update_check=False, early_stop=None, generations=1000000,
        max_eval_time_mins=5, max_time_mins=2, memory=None,
        mutation_rate=0.9, n_jobs=1, offspring_size=None,
        periodic_checkpoint_folder=None, population_size=100,
        random_state=None, scoring=None, subsample=1.0, use_dask=False,
        verbosity=2, warm_start=False)

In [33]:
y_test

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1], dtype=int8)

In [34]:
print(tpot.score(X_test_array, y_test))

0.8333333333333334


In [35]:
tpot1 = TPOTClassifier(verbosity=2, max_time_mins=10,n_jobs = 4)
tpot1.fit(X_train_array, y_train)
print(tpot1.score(X_test_array, y_test))

Generation 1 - Current best internal CV score: 0.8101750082551064
Generation 2 - Current best internal CV score: 0.8101750082551064
Generation 3 - Current best internal CV score: 0.8101750082551064
Generation 4 - Current best internal CV score: 0.8101750082551064
Generation 5 - Current best internal CV score: 0.8101750082551064
Generation 6 - Current best internal CV score: 0.8101750082551064
Generation 7 - Current best internal CV score: 0.8101750082551064
Generation 8 - Current best internal CV score: 0.8124464990486974
Generation 9 - Current best internal CV score: 0.8124464990486974

10.164170816666665 minutes have elapsed. TPOT will close down.
TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: ExtraTreesClassifier(PCA(input_matrix, iterated_power=1, svd_solver=randomized), bootstrap=False, criterion=entropy, max_features=0.3, min_samples_leaf=3, min_samples_split=2, n_estimators=100)
0.8333333333333334


In [36]:
tpot.export('tpot_av_loans_1.py')

True

In [37]:
tpot1.export('tpot_av_loans_10mins_1.py')

True

In [38]:
av_test = pd.read_csv('processed_test.csv')

In [39]:
av_test.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001015       1        1           1          0              0   
1  LP001022       1        1           2          0              0   
2  LP001031       1        1           3          0              0   
3  LP001035       1        1           3          0              0   
4  LP001051       1        0           1          1              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History  Property_Area  
0             1.0              2  
1             1.0              2  
2             1.0              2  
3             0.0              2  
4             1.0              2

In [40]:
temp=av_test['Loan_ID']

In [41]:
del av_test['Loan_ID']

In [42]:
av_test_array=av_test.values

In [43]:
print(type(av_test_array))

<class 'numpy.ndarray'>


In [47]:
results = tpot1.predict(av_test_array)

In [48]:
results

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [49]:
type(results)

numpy.ndarray

In [50]:
type(temp)

pandas.core.series.Series

In [51]:
results=pd.Series(results)

In [52]:
type(results)

pandas.core.series.Series

In [69]:
results.replace([0, 1], ['N','Y'],inplace=True)

In [70]:
final=pd.concat([temp, results], axis=1)

In [71]:
final.shape

(367, 2)

In [72]:
final.head()

Loan_ID  0
0  LP001015  Y
1  LP001022  Y
2  LP001031  Y
3  LP001035  N
4  LP001051  Y

In [73]:
final.columns.values

array(['Loan_ID', 0], dtype=object)

In [74]:
final.rename(columns={0: 'Loan_Status'}, inplace=True)

In [75]:
final.columns.values

array(['Loan_ID', 'Loan_Status'], dtype=object)

In [76]:
file_name="tpot_final_av_test.csv"
final.to_csv(file_name, sep=',', encoding='utf-8',index=False)