In [37]:
import pandas as pd
import numpy as np
import os
import random
random.seed(100)
os.chdir('/home/sunil/Desktop/datahack')
train = pd.read_csv('train.csv')

In [38]:
train.shape

(614, 13)

In [39]:
train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [40]:
train.rename(columns={'Loan_Status': 'class'}, inplace=True)

In [41]:
train.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
class                 object
dtype: object

In [42]:
train.isnull().values.any()

True

In [43]:
train=train.dropna()

In [44]:
train.shape

(480, 13)

In [45]:
train.isnull().values.any()

False

In [46]:
for col_name in train.columns:
    if(train[col_name].dtype == 'object'):
        train[col_name]= train[col_name].astype('category')
        train[col_name] = train[col_name].cat.codes

In [47]:
train.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
1        0       1        1           1          0              0   
2        1       1        1           0          0              1   
3        2       1        1           0          1              0   
4        3       1        0           0          0              0   
5        4       1        1           2          0              1   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   

   Credit_History  Property_Area  class  
1             1.0              0      0  
2             1.0              2      1  
3             1.0              2      1  
4             1.0              2      1  
5             1.0              2      1

In [48]:
X = train.drop('class', axis=1)  
X = X.drop('Loan_ID',axis=1)
y = train['class'] 

In [49]:
X.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
1       1        1           1          0              0             4583   
2       1        1           0          0              1             3000   
3       1        1           0          1              0             2583   
4       1        0           0          0              0             6000   
5       1        1           2          0              1             5417   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   

   Property_Area  
1              0  
2              2  
3              2  
4              2  
5              2

In [50]:
y.head()

1    0
2    1
3    1
4    1
5    1
Name: class, dtype: int8

In [51]:
X.apply(lambda x: x.value_counts()).T.stack()

Gender            0.0        86.0
                  1.0       394.0
Married           0.0       169.0
                  1.0       311.0
Dependents        0.0       274.0
                  1.0        80.0
                  2.0        85.0
                  3.0        41.0
Education         0.0       383.0
                  1.0        97.0
Self_Employed     0.0       414.0
                  1.0        66.0
ApplicantIncome   150.0       1.0
                  645.0       1.0
                  1000.0      1.0
                  1025.0      1.0
                  1299.0      1.0
                  1378.0      1.0
                  1442.0      1.0
                  1500.0      1.0
                  1538.0      1.0
                  1600.0      1.0
                  1625.0      1.0
                  1668.0      1.0
                  1759.0      1.0
                  1782.0      1.0
                  1800.0      2.0
                  1809.0      1.0
                  1811.0      1.0
              

In [52]:
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y.values,train_size=0.90, test_size=0.10)

In [53]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((432, 11), (48, 11), (432,), (48,))

In [54]:
X_train_array=X_train.values
X_test_array=X_test.values

In [55]:
print(type(X_train_array))
print(type(X_test_array))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [56]:
#X_train_array=X_train_array.toarray()
#X_test_array=X_test_array.toarray()

In [57]:
y_test

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1], dtype=int8)

In [58]:
X_test_array

array([[1.0000e+00, 1.0000e+00, 2.0000e+00, 0.0000e+00, 0.0000e+00,
        4.5660e+03, 0.0000e+00, 1.0000e+02, 3.6000e+02, 1.0000e+00,
        2.0000e+00],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        4.5830e+03, 0.0000e+00, 1.1200e+02, 3.6000e+02, 1.0000e+00,
        0.0000e+00],
       [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 0.0000e+00,
        1.9580e+03, 2.4360e+03, 1.3100e+02, 3.6000e+02, 1.0000e+00,
        0.0000e+00],
       [1.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
        4.3000e+03, 2.0140e+03, 1.9400e+02, 3.6000e+02, 1.0000e+00,
        0.0000e+00],
       [1.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
        9.5600e+03, 0.0000e+00, 1.9100e+02, 3.6000e+02, 1.0000e+00,
        1.0000e+00],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        3.2540e+03, 0.0000e+00, 5.0000e+01, 3.6000e+02, 1.0000e+00,
        2.0000e+00],
       [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 0.

In [59]:
type(X_test_array)

numpy.ndarray

In [60]:
X_test

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
384       1        1           2          0              0             4566   
166       0        1           0          0              0             4583   
485       1        1           1          1              0             1958   
124       1        1           0          1              0             4300   
25        1        1           0          0              1             9560   
154       1        0           0          0              0             3254   
543       1        1           1          1              0             2239   
350       1        1           0          0              0             9083   
149       1        1           0          0              0             4860   
233       0        0           0          0              0             8333   
40        1        0           0          0              0             3600   
297       0        1           1          0              0             4666   
167       1        1           0          0              0             2439   
587       0        0           0          1              0             2165   
227       1        1           2          0              0             6250   
46        1        1           1          0              0             5649   
416       0        0           1          0              0             2600   
235       1        1           1          0              0             5500   
426       0        0           1          1              0             4606   
22        1        1           0          1              0             2600   
406       1        1           0          1              0             2167   
612       1        1           2          0              0             7583   
84        1        1           1          0              0             3988   
362       1        1           0          0              0             4750   
552       1        1           1          0              0             3333   
365       1        0           0          1              0             6216   
452       1        1           0          0              0             3948   
430       0        0           1          0              1             8624   
574       1        1           3          0              0             6406   
246       1        1           2          0              0             9703   
462       1        1           0          0              0             3015   
502       1        1           2          0              0             4865   
581       1        0           0          0              0             1836   
561       0        1           1          0              1            19484   
389       1        1           0          0              0             5488   
13        1        0           0          0              0             1853   
270       0        0           0          0              0             3237   
18        1        1           0          1              0             4887   
169       1        1           2          0              0             8000   
393       1        1           2          1              0             1993   
398       1        0           0          1              0             3902   
480       0        0           0          1              0             4350   
281       1        1           0          0              0             3927   
382       0        0           0          0              0             6000   
289       1        0           0          0              0             9508   
599       1        1           2          0              0             5780   
157       1        1           1          0              0             9538   
49        0        0           0          0              0             4000   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
384                0.0       100.0             360.0         

In [61]:
X_train_array

array([[  1.,   1.,   1., ..., 360.,   1.,   1.],
       [  1.,   1.,   0., ..., 360.,   1.,   1.],
       [  1.,   1.,   0., ..., 360.,   1.,   2.],
       ...,
       [  1.,   1.,   1., ..., 360.,   1.,   2.],
       [  1.,   0.,   0., ..., 360.,   1.,   1.],
       [  1.,   1.,   3., ..., 360.,   0.,   1.]])

In [62]:
X_train

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
470       1        1           1          0              1             3450   
26        1        1           0          0              0             2799   
6         1        1           0          1              0             2333   
351       1        0           0          0              0             8750   
354       0        1           0          0              0             2423   
186       1        1           1          0              1             2178   
408       1        1           1          0              0             8300   
52        0        0           0          0              0             4230   
277       1        1           0          0              0             3103   
184       0        1           0          0              0             3625   
98        1        1           0          1              0             4188   
90        1        1           0          0              0             2958   
280       1        0           1          1              1             4053   
492       1        0           0          1              0             3691   
266       1        1           2          0              0             4708   
92        1        1           2          1              0             3273   
558       1        1           0          0              0             3887   
457       1        1           0          0              0             3708   
471       1        1           1          1              0             2653   
360       0        0           1          0              0             4723   
413       1        1           0          1              0             2253   
143       1        1           0          0              0             2698   
310       0        0           0          0              0             2917   
4         1        0           0          0              0             6000   
383       1        0           0          0              1             7167   
123       1        1           2          0              0             2957   
276       1        1           0          0              0             3993   
472       1        1           3          0              0             4691   
94        1        0           0          1              0             3620   
179       1        0           0          1              0             2333   
..      ...      ...         ...        ...            ...              ...   
575       1        1           2          0              0             3159   
182       1        1           0          0              0             4600   
247       1        1           1          1              0             6608   
394       1        1           2          0              0             3100   
448       1        1           2          0              0             3340   
454       1        0           0          0              1             7085   
110       1        0           0          0              0             5316   
119       0        0           0          0              0            10408   
438       1        0           0          0              1            10416   
151       1        1           0          0              1             2577   
372       1        1           2          0              1             9323   
340       1        1           3          1              0             2647   
429       1        0           0          1              0             2717   
10        1        1           2          0              0             3200   
286       0        0           0          0              1             2600   
138       1        0           0          0              0            14999   
178       1        1           1          0              0             3750   
381       1        0           0          0              0             5941   
307       0        0           0          0            

In [63]:
type(X_train_array)

numpy.ndarray

In [64]:
type(y_train)

numpy.ndarray

In [65]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,

In [66]:
import numpy as np 
np.shape(X_train_array)

(432, 11)

In [67]:
np.shape(X_test_array)

(48, 11)

In [68]:
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics

import autosklearn.classification


In [69]:
y_test

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1], dtype=int8)

In [70]:
import multiprocessing
import shutil

import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics

import autosklearn
from autosklearn.metrics import accuracy
from autosklearn.classification import AutoSklearnClassifier
from autosklearn.constants import *

automl = autosklearn.classification.AutoSklearnClassifier(
        time_left_for_this_task=120,
        per_run_time_limit=30,
        tmp_folder='/home/sunil/Desktop/datahack/autosklearn-tmp1',
        output_folder ='/home/sunil/Desktop/datahack/autosklearn-op1',
        ensemble_size=1,
        delete_tmp_folder_after_terminate=False,
        resampling_strategy='cv',
        resampling_strategy_arguments={'folds': 5},)

In [71]:
import warnings
warnings.filterwarnings("ignore")

In [72]:
automl.fit(X_train.copy(), y_train.copy())

[WARNING] [2018-11-13 22:39:24,416:EnsembleBuilder(1):dc92d1b3a068cc9b2cbcbb2809cacfe4] No models better than random - using Dummy Classifier!
[WARNING] [2018-11-13 22:39:24,428:EnsembleBuilder(1):dc92d1b3a068cc9b2cbcbb2809cacfe4] No models better than random - using Dummy Classifier!
[WARNING] [2018-11-13 22:39:26,435:EnsembleBuilder(1):dc92d1b3a068cc9b2cbcbb2809cacfe4] No models better than random - using Dummy Classifier!
[WARNING] [2018-11-13 22:39:43,698:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2018-11-13 22:39:43,698:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger


AutoSklearnClassifier(delete_output_folder_after_terminate=True,
           delete_tmp_folder_after_terminate=False,
           disable_evaluator_output=False, ensemble_nbest=50,
           ensemble_size=1, exclude_estimators=None,
           exclude_preprocessors=None, get_smac_object_callback=None,
           include_estimators=None, include_preprocessors=None,
           initial_configurations_via_metalearning=25,
           ml_memory_limit=3072,
           output_folder='/home/sunil/Desktop/datahack/autosklearn-op1',
           per_run_time_limit=30, resampling_strategy='cv',
           resampling_strategy_arguments={'folds': 5}, seed=1,
           shared_mode=False, smac_scenario_args=None,
           time_left_for_this_task=120,
           tmp_folder='/home/sunil/Desktop/datahack/autosklearn-tmp1')

In [73]:
automl.cv_results_

{'mean_test_score': array([0.80555556, 0.77314815, 0.74074074, 0.78240741, 0.75      ,
        0.80555556, 0.76851852, 0.77777778, 0.64814815, 0.34490741,
        0.73148148, 0.48148148, 0.73611111, 0.75925926, 0.81018519,
        0.81018519, 0.7662037 , 0.38657407, 0.75694444, 0.80555556,
        0.75231481, 0.81018519, 0.68518519, 0.77546296, 0.68518519,
        0.7962963 , 0.        ]),
 'mean_fit_time': array([2.98928547, 8.26364923, 4.12810612, 3.38197207, 9.44044995,
        2.76486874, 4.88924742, 4.21412635, 3.30774903, 2.52000809,
        3.59251547, 2.49275064, 3.41734743, 4.32336354, 2.22292876,
        2.48669195, 2.5473938 , 4.78945971, 4.52200079, 1.99482679,
        3.32519674, 2.47754431, 2.76153827, 2.81615376, 3.25581908,
        2.19102454, 2.00944448]),
 'params': [{'balancing:strategy': 'none',
   'categorical_encoding:__choice__': 'one_hot_encoding',
   'classifier:__choice__': 'random_forest',
   'imputation:strategy': 'mean',
   'preprocessor:__choice__': 'no_pr

In [74]:
automl.refit(X_train.copy(), y_train.copy())

AutoSklearnClassifier(delete_output_folder_after_terminate=True,
           delete_tmp_folder_after_terminate=False,
           disable_evaluator_output=False, ensemble_nbest=50,
           ensemble_size=1, exclude_estimators=None,
           exclude_preprocessors=None, get_smac_object_callback=None,
           include_estimators=None, include_preprocessors=None,
           initial_configurations_via_metalearning=25,
           ml_memory_limit=3072,
           output_folder='/home/sunil/Desktop/datahack/autosklearn-op1',
           per_run_time_limit=30, resampling_strategy='cv',
           resampling_strategy_arguments={'folds': 5}, seed=1,
           shared_mode=False, smac_scenario_args=None,
           time_left_for_this_task=120,
           tmp_folder='/home/sunil/Desktop/datahack/autosklearn-tmp1')

In [75]:
print(automl.show_models())

[(1.000000, SimpleClassificationPipeline({'balancing:strategy': 'none', 'categorical_encoding:__choice__': 'one_hot_encoding', 'classifier:__choice__': 'gradient_boosting', 'imputation:strategy': 'mean', 'preprocessor:__choice__': 'select_rates', 'rescaling:__choice__': 'robust_scaler', 'categorical_encoding:one_hot_encoding:use_minimum_fraction': 'True', 'classifier:gradient_boosting:criterion': 'mse', 'classifier:gradient_boosting:learning_rate': 0.053517066400173056, 'classifier:gradient_boosting:loss': 'deviance', 'classifier:gradient_boosting:max_depth': 10, 'classifier:gradient_boosting:max_features': 0.542144980834302, 'classifier:gradient_boosting:max_leaf_nodes': 'None', 'classifier:gradient_boosting:min_impurity_decrease': 0.0, 'classifier:gradient_boosting:min_samples_leaf': 20, 'classifier:gradient_boosting:min_samples_split': 13, 'classifier:gradient_boosting:min_weight_fraction_leaf': 0.0, 'classifier:gradient_boosting:n_estimators': 233, 'classifier:gradient_boosting:sub

In [76]:
predictions = automl.predict(X_test)

In [78]:
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1], dtype=int8)

In [77]:
print("Accuracy score", sklearn.metrics.accuracy_score(y_test, predictions))

Accuracy score 0.7916666666666666


In [83]:
av_test = pd.read_csv('processed_test.csv')
temp=av_test['Loan_ID']
del av_test['Loan_ID']
av_test_array=av_test.values
results = automl.predict(av_test_array)
results=pd.Series(results)
results.replace([0, 1], ['N','Y'],inplace=True)
final=pd.concat([temp, results], axis=1)
final.rename(columns={0: 'Loan_Status'}, inplace=True)
file_name="autosklearn_final_av_test.csv"
final.to_csv(file_name, sep=',', encoding='utf-8',index=False)